name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake
      - name: Build and test
        run: |
          cmake -H. -B_build -DBUILD_TESTS=ON
          cmake --build _build
          cmake --build _build --target test
          _build/check
          cmake --build _build --target test -- ARGS=--verbose
  coveralls:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v2
      - name: Install coveralls
        run: |
          python3 -m pip install cpp-coveralls
      - name: Run coveralls
        run: |
          coveralls --root . -E ".gtest." -E ".CMakeFiles."
      - name: Tests
        run: |
          _build/check
